export interface PresetPackages {
	cli: string[];
	cask: string[];
	npm?: string[];
}

export const PRESET_PACKAGES: Record<string, PresetPackages> = {
	minimal: {
		cli: [
			'curl',
			'wget',
			'jq',
			'yq',
			'ripgrep',
			'fd',
			'bat',
			'eza',
			'fzf',
			'zoxide',
			'htop',
			'btop',
			'tree',
			'tealdeer',
			'gh',
			'git-delta',
			'git-lfs',
			'lazygit',
			'stow'
		],
		cask: ['warp', 'raycast', 'maccy', 'stats', 'rectangle']
	},
	developer: {
		cli: [
			'curl',
			'wget',
			'jq',
			'yq',
			'ripgrep',
			'fd',
			'bat',
			'eza',
			'fzf',
			'zoxide',
			'htop',
			'btop',
			'tree',
			'tealdeer',
			'gh',
			'git-delta',
			'git-lfs',
			'lazygit',
			'pre-commit',
			'stow',
			'node',
			'go',
			'pnpm',
			'docker',
			'docker-compose',
			'lazydocker',
			'tmux',
			'neovim',
			'httpie'
		],
		cask: [
			'warp',
			'raycast',
			'maccy',
			'stats',
			'scroll-reverser',
			'rectangle',
			'visual-studio-code',
			'orbstack',
			'google-chrome',
			'arc',
			'postman',
			'notion',
			'tableplus',
			'appcleaner'
		],
		npm: ['typescript', 'tsx', 'eslint', 'prettier', 'nodemon']
	},
	full: {
		cli: [
			'curl',
			'wget',
			'jq',
			'yq',
			'ripgrep',
			'fd',
			'bat',
			'eza',
			'fzf',
			'zoxide',
			'htop',
			'btop',
			'tree',
			'tealdeer',
			'gh',
			'git-delta',
			'git-lfs',
			'lazygit',
			'tig',
			'pre-commit',
			'stow',
			'node',
			'go',
			'pnpm',
			'docker',
			'docker-compose',
			'lazydocker',
			'dive',
			'tmux',
			'neovim',
			'httpie',
			'python',
			'uv',
			'rustup',
			'deno',
			'bun',
			'cmake',
			'kubectl',
			'helm',
			'k9s',
			'terraform',
			'awscli',
			'sqlite',
			'postgresql',
			'redis',
			'duckdb',
			'ollama',
			'llm'
		],
		cask: [
			'warp',
			'raycast',
			'maccy',
			'stats',
			'scroll-reverser',
			'rectangle',
			'visual-studio-code',
			'cursor',
			'orbstack',
			'ngrok',
			'google-chrome',
			'arc',
			'firefox',
			'postman',
			'proxyman',
			'tableplus',
			'notion',
			'obsidian',
			'figma',
			'iina',
			'keka',
			'aldente',
			'appcleaner',
			'shottr',
			'miniconda'
		],
		npm: ['typescript', 'tsx', 'eslint', 'prettier', 'nodemon', 'pm2', 'serve', 'vercel', 'wrangler']
	}
};

export function getPresetPackages(preset: string): string[] {
	const p = PRESET_PACKAGES[preset];
	return p ? [...p.cli, ...p.cask, ...(p.npm || [])] : [];
}

export const PRESET_NAMES = ['minimal', 'developer', 'full'] as const;
export type PresetName = (typeof PRESET_NAMES)[number];
