-- Seed official openboot user and 20 curated starter configs

INSERT INTO users (id, username, email, avatar_url)
VALUES ('openboot-official', 'openboot', 'hello@openboot.dev', 'https://avatars.githubusercontent.com/u/258731499?v=4');

-- 1. Frontend - React
INSERT INTO configs (id, user_id, slug, name, description, base_preset, packages, custom_script, visibility, alias, dotfiles_repo, install_count, featured)
VALUES ('ob-seed-react-frontend', 'openboot-official', 'react-frontend', 'Frontend — React', 'Production-ready React and Next.js setup with fast builds, browser testing, and design handoff tools.', 'developer', '[{"name":"node","type":"formula","desc":"JavaScript runtime"},{"name":"pnpm","type":"formula","desc":"Fast package manager"},{"name":"watchman","type":"formula","desc":"File watcher for React"},{"name":"typescript","type":"formula","desc":"Typed JavaScript compiler"},{"name":"git","type":"formula","desc":"Version control"},{"name":"gh","type":"formula","desc":"GitHub CLI"},{"name":"eza","type":"formula","desc":"Modern ls replacement"},{"name":"fzf","type":"formula","desc":"Fuzzy finder"},{"name":"visual-studio-code","type":"cask","desc":"Code editor"},{"name":"google-chrome","type":"cask","desc":"Web browser"},{"name":"firefox","type":"cask","desc":"Testing browser"},{"name":"figma","type":"cask","desc":"Design collaboration"},{"name":"arc","type":"cask","desc":"Productivity browser"},{"name":"rectangle","type":"cask","desc":"Window manager"},{"name":"raycast","type":"cask","desc":"Launcher and productivity"}]', '', 'public', 'react-frontend', '', 0, 1);

-- 2. Frontend - Vue
INSERT INTO configs (id, user_id, slug, name, description, base_preset, packages, custom_script, visibility, alias, dotfiles_repo, install_count, featured)
VALUES ('ob-seed-vue-frontend', 'openboot-official', 'vue-frontend', 'Frontend — Vue', 'Lightweight Vue 3 and Nuxt dev environment with Deno support and modern CLI essentials.', 'developer', '[{"name":"node","type":"formula","desc":"JavaScript runtime"},{"name":"pnpm","type":"formula","desc":"Fast package manager"},{"name":"deno","type":"formula","desc":"Secure JS/TS runtime"},{"name":"git","type":"formula","desc":"Version control"},{"name":"gh","type":"formula","desc":"GitHub CLI"},{"name":"jq","type":"formula","desc":"JSON processor"},{"name":"eza","type":"formula","desc":"Modern ls replacement"},{"name":"fzf","type":"formula","desc":"Fuzzy finder"},{"name":"bat","type":"formula","desc":"Better cat with syntax"},{"name":"visual-studio-code","type":"cask","desc":"Code editor"},{"name":"google-chrome","type":"cask","desc":"Web browser"},{"name":"firefox","type":"cask","desc":"Testing browser"},{"name":"figma","type":"cask","desc":"Design collaboration"},{"name":"raycast","type":"cask","desc":"Launcher and productivity"}]', '', 'public', 'vue-frontend', '', 0, 1);

-- 3. Backend - Go
INSERT INTO configs (id, user_id, slug, name, description, base_preset, packages, custom_script, visibility, alias, dotfiles_repo, install_count, featured)
VALUES ('ob-seed-go-backend', 'openboot-official', 'go-backend', 'Backend — Go', 'Battle-tested Go backend stack with gRPC tooling, live reload, and linting out of the box.', 'developer', '[{"name":"go","type":"formula","desc":"Go programming language"},{"name":"golangci-lint","type":"formula","desc":"Go linter aggregator"},{"name":"protobuf","type":"formula","desc":"Protocol buffer compiler"},{"name":"grpcurl","type":"formula","desc":"gRPC curl client"},{"name":"git","type":"formula","desc":"Version control"},{"name":"gh","type":"formula","desc":"GitHub CLI"},{"name":"jq","type":"formula","desc":"JSON processor"},{"name":"ripgrep","type":"formula","desc":"Fast code search"},{"name":"lazygit","type":"formula","desc":"Git TUI"},{"name":"httpie","type":"formula","desc":"HTTP client for APIs"},{"name":"visual-studio-code","type":"cask","desc":"Code editor"},{"name":"tableplus","type":"cask","desc":"Database GUI"},{"name":"orbstack","type":"cask","desc":"Docker alternative"}]', '', 'public', 'go-backend', '', 0, 1);

-- 4. Backend - Python
INSERT INTO configs (id, user_id, slug, name, description, base_preset, packages, custom_script, visibility, alias, dotfiles_repo, install_count, featured)
VALUES ('ob-seed-python-backend', 'openboot-official', 'python-backend', 'Backend — Python', 'Modern Python dev setup with uv for dependency management and ruff for lightning-fast linting.', 'developer', '[{"name":"python","type":"formula","desc":"Python interpreter"},{"name":"uv","type":"formula","desc":"Fast Python package manager"},{"name":"ruff","type":"formula","desc":"Extremely fast linter"},{"name":"pipx","type":"formula","desc":"Isolated CLI installs"},{"name":"httpie","type":"formula","desc":"HTTP client for APIs"},{"name":"git","type":"formula","desc":"Version control"},{"name":"gh","type":"formula","desc":"GitHub CLI"},{"name":"jq","type":"formula","desc":"JSON processor"},{"name":"ripgrep","type":"formula","desc":"Fast code search"},{"name":"lazygit","type":"formula","desc":"Git TUI"},{"name":"cursor","type":"cask","desc":"AI-powered code editor"},{"name":"tableplus","type":"cask","desc":"Database GUI"},{"name":"orbstack","type":"cask","desc":"Docker alternative"},{"name":"warp","type":"cask","desc":"Modern terminal"}]', '', 'public', 'python-backend', '', 0, 1);

-- 5. Backend - Node.js
INSERT INTO configs (id, user_id, slug, name, description, base_preset, packages, custom_script, visibility, alias, dotfiles_repo, install_count, featured)
VALUES ('ob-seed-nodejs-backend', 'openboot-official', 'nodejs-backend', 'Backend — Node.js', 'Node.js API stack with PostgreSQL, Redis, and everything you need to ship production services.', 'developer', '[{"name":"node","type":"formula","desc":"JavaScript runtime"},{"name":"pnpm","type":"formula","desc":"Fast package manager"},{"name":"redis","type":"formula","desc":"In-memory data store"},{"name":"postgresql","type":"formula","desc":"Relational database"},{"name":"git","type":"formula","desc":"Version control"},{"name":"gh","type":"formula","desc":"GitHub CLI"},{"name":"jq","type":"formula","desc":"JSON processor"},{"name":"httpie","type":"formula","desc":"HTTP client for APIs"},{"name":"lazygit","type":"formula","desc":"Git TUI"},{"name":"visual-studio-code","type":"cask","desc":"Code editor"},{"name":"postman","type":"cask","desc":"API testing platform"},{"name":"tableplus","type":"cask","desc":"Database GUI"},{"name":"orbstack","type":"cask","desc":"Docker alternative"},{"name":"warp","type":"cask","desc":"Modern terminal"}]', '', 'public', 'nodejs-backend', '', 0, 1);

-- 6. Backend - Java/Spring
INSERT INTO configs (id, user_id, slug, name, description, base_preset, packages, custom_script, visibility, alias, dotfiles_repo, install_count, featured)
VALUES ('ob-seed-java-spring', 'openboot-official', 'java-spring', 'Backend — Java/Spring', 'Enterprise-grade Java setup with Maven, Gradle, and JetBrains tooling for Spring Boot development.', 'developer', '[{"name":"openjdk","type":"formula","desc":"Java development kit"},{"name":"maven","type":"formula","desc":"Java build tool"},{"name":"gradle","type":"formula","desc":"Flexible build automation"},{"name":"git","type":"formula","desc":"Version control"},{"name":"gh","type":"formula","desc":"GitHub CLI"},{"name":"jq","type":"formula","desc":"JSON processor"},{"name":"httpie","type":"formula","desc":"HTTP client for APIs"},{"name":"ripgrep","type":"formula","desc":"Fast code search"},{"name":"btop","type":"formula","desc":"System resource monitor"},{"name":"jetbrains-toolbox","type":"cask","desc":"JetBrains IDE manager"},{"name":"tableplus","type":"cask","desc":"Database GUI"},{"name":"orbstack","type":"cask","desc":"Docker alternative"},{"name":"postman","type":"cask","desc":"API testing platform"}]', '', 'public', 'java-spring', '', 0, 1);

-- 7. Backend - Rust
INSERT INTO configs (id, user_id, slug, name, description, base_preset, packages, custom_script, visibility, alias, dotfiles_repo, install_count, featured)
VALUES ('ob-seed-rust-backend', 'openboot-official', 'rust-backend', 'Backend — Rust', 'Systems programming toolkit with Rust, live rebuild on save, and dependency management helpers.', 'developer', '[{"name":"rustup","type":"formula","desc":"Rust toolchain installer"},{"name":"cmake","type":"formula","desc":"Cross-platform build system"},{"name":"git","type":"formula","desc":"Version control"},{"name":"gh","type":"formula","desc":"GitHub CLI"},{"name":"protobuf","type":"formula","desc":"Protocol buffer compiler"},{"name":"ripgrep","type":"formula","desc":"Fast code search"},{"name":"fd","type":"formula","desc":"Fast file finder"},{"name":"bat","type":"formula","desc":"Better cat with syntax"},{"name":"lazygit","type":"formula","desc":"Git TUI"},{"name":"htop","type":"formula","desc":"Process viewer"},{"name":"visual-studio-code","type":"cask","desc":"Code editor"},{"name":"orbstack","type":"cask","desc":"Docker alternative"},{"name":"warp","type":"cask","desc":"Modern terminal"}]', '', 'public', 'rust-backend', '', 0, 1);

-- 8. Backend - Ruby on Rails
INSERT INTO configs (id, user_id, slug, name, description, base_preset, packages, custom_script, visibility, alias, dotfiles_repo, install_count, featured)
VALUES ('ob-seed-rails-backend', 'openboot-official', 'rails-backend', 'Backend — Ruby on Rails', 'Rails-ready Mac with rbenv, PostgreSQL, Redis, and Overmind for managing Procfile-based apps.', 'developer', '[{"name":"ruby","type":"formula","desc":"Ruby language"},{"name":"rbenv","type":"formula","desc":"Ruby version manager"},{"name":"postgresql","type":"formula","desc":"Relational database"},{"name":"redis","type":"formula","desc":"In-memory data store"},{"name":"overmind","type":"formula","desc":"Procfile process manager"},{"name":"git","type":"formula","desc":"Version control"},{"name":"gh","type":"formula","desc":"GitHub CLI"},{"name":"imagemagick","type":"formula","desc":"Image processing CLI"},{"name":"lazygit","type":"formula","desc":"Git TUI"},{"name":"eza","type":"formula","desc":"Modern ls replacement"},{"name":"visual-studio-code","type":"cask","desc":"Code editor"},{"name":"tableplus","type":"cask","desc":"Database GUI"},{"name":"orbstack","type":"cask","desc":"Docker alternative"}]', '', 'public', 'rails-backend', '', 0, 1);

-- 9. Full-Stack T3
INSERT INTO configs (id, user_id, slug, name, description, base_preset, packages, custom_script, visibility, alias, dotfiles_repo, install_count, featured)
VALUES ('ob-seed-t3-fullstack', 'openboot-official', 't3-fullstack', 'Full-Stack — T3', 'The complete T3 stack: Next.js, Prisma, tRPC with PostgreSQL, Redis, and design-to-deploy tooling.', 'developer', '[{"name":"node","type":"formula","desc":"JavaScript runtime"},{"name":"pnpm","type":"formula","desc":"Fast package manager"},{"name":"postgresql","type":"formula","desc":"Relational database"},{"name":"redis","type":"formula","desc":"In-memory data store"},{"name":"git","type":"formula","desc":"Version control"},{"name":"gh","type":"formula","desc":"GitHub CLI"},{"name":"typescript","type":"formula","desc":"Typed JavaScript compiler"},{"name":"jq","type":"formula","desc":"JSON processor"},{"name":"lazygit","type":"formula","desc":"Git TUI"},{"name":"visual-studio-code","type":"cask","desc":"Code editor"},{"name":"google-chrome","type":"cask","desc":"Web browser"},{"name":"figma","type":"cask","desc":"Design collaboration"},{"name":"tableplus","type":"cask","desc":"Database GUI"},{"name":"orbstack","type":"cask","desc":"Docker alternative"},{"name":"arc","type":"cask","desc":"Productivity browser"}]', '', 'public', 't3-fullstack', '', 0, 1);

-- 10. iOS/macOS Developer
INSERT INTO configs (id, user_id, slug, name, description, base_preset, packages, custom_script, visibility, alias, dotfiles_repo, install_count, featured)
VALUES ('ob-seed-ios-developer', 'openboot-official', 'ios-developer', 'iOS/macOS Developer', 'Swift and SwiftUI toolkit with linting, CI automation, and network debugging — pairs with Xcode.', 'developer', '[{"name":"swiftlint","type":"formula","desc":"Swift style enforcer"},{"name":"cocoapods","type":"formula","desc":"iOS dependency manager"},{"name":"fastlane","type":"formula","desc":"iOS CI/CD automation"},{"name":"xcbeautify","type":"formula","desc":"Xcode build formatter"},{"name":"git","type":"formula","desc":"Version control"},{"name":"gh","type":"formula","desc":"GitHub CLI"},{"name":"ripgrep","type":"formula","desc":"Fast code search"},{"name":"jq","type":"formula","desc":"JSON processor"},{"name":"tree","type":"formula","desc":"Directory visualizer"},{"name":"sf-symbols","type":"cask","desc":"Apple icon browser"},{"name":"proxyman","type":"cask","desc":"HTTP debugging proxy"},{"name":"charles","type":"cask","desc":"Network traffic analyzer"},{"name":"raycast","type":"cask","desc":"Launcher and productivity"}]', '', 'public', 'ios-developer', '', 0, 1);

-- 11. Android Developer
INSERT INTO configs (id, user_id, slug, name, description, base_preset, packages, custom_script, visibility, alias, dotfiles_repo, install_count, featured)
VALUES ('ob-seed-android-dev', 'openboot-official', 'android-dev', 'Android Developer', 'Android Studio with Gradle, device mirroring via scrcpy, and design tools for Material You apps.', 'developer', '[{"name":"openjdk","type":"formula","desc":"Java development kit"},{"name":"gradle","type":"formula","desc":"Flexible build automation"},{"name":"scrcpy","type":"formula","desc":"Android screen mirror"},{"name":"git","type":"formula","desc":"Version control"},{"name":"gh","type":"formula","desc":"GitHub CLI"},{"name":"jq","type":"formula","desc":"JSON processor"},{"name":"ripgrep","type":"formula","desc":"Fast code search"},{"name":"tree","type":"formula","desc":"Directory visualizer"},{"name":"btop","type":"formula","desc":"System resource monitor"},{"name":"android-studio","type":"cask","desc":"Android IDE"},{"name":"figma","type":"cask","desc":"Design collaboration"},{"name":"rectangle","type":"cask","desc":"Window manager"},{"name":"warp","type":"cask","desc":"Modern terminal"}]', '', 'public', 'android-dev', '', 0, 1);

-- 12. DevOps / SRE
INSERT INTO configs (id, user_id, slug, name, description, base_preset, packages, custom_script, visibility, alias, dotfiles_repo, install_count, featured)
VALUES ('ob-seed-devops-sre', 'openboot-official', 'devops-sre', 'DevOps / SRE', 'Infrastructure-as-code essentials: Terraform, Kubernetes, Helm, and AWS CLI for reliable deployments.', 'developer', '[{"name":"terraform","type":"formula","desc":"Infrastructure as code"},{"name":"kubectl","type":"formula","desc":"Kubernetes CLI"},{"name":"helm","type":"formula","desc":"Kubernetes package manager"},{"name":"k9s","type":"formula","desc":"Kubernetes TUI"},{"name":"awscli","type":"formula","desc":"AWS command line"},{"name":"docker","type":"formula","desc":"Container engine"},{"name":"jq","type":"formula","desc":"JSON processor"},{"name":"yq","type":"formula","desc":"YAML processor"},{"name":"git","type":"formula","desc":"Version control"},{"name":"gh","type":"formula","desc":"GitHub CLI"},{"name":"ripgrep","type":"formula","desc":"Fast code search"},{"name":"htop","type":"formula","desc":"Process viewer"},{"name":"orbstack","type":"cask","desc":"Docker alternative"},{"name":"lens","type":"cask","desc":"Kubernetes IDE"},{"name":"visual-studio-code","type":"cask","desc":"Code editor"},{"name":"warp","type":"cask","desc":"Modern terminal"}]', '', 'public', 'devops-sre', '', 0, 1);

-- 13. Platform Engineer
INSERT INTO configs (id, user_id, slug, name, description, base_preset, packages, custom_script, visibility, alias, dotfiles_repo, install_count, featured)
VALUES ('ob-seed-platform-eng', 'openboot-official', 'platform-eng', 'Platform Engineer', 'Full platform engineering stack: IaC, config management, secret encryption, and supply chain security.', 'developer', '[{"name":"terraform","type":"formula","desc":"Infrastructure as code"},{"name":"ansible","type":"formula","desc":"Config management"},{"name":"sops","type":"formula","desc":"Encrypted secrets editor"},{"name":"age","type":"formula","desc":"Modern file encryption"},{"name":"cosign","type":"formula","desc":"Container image signing"},{"name":"kubectl","type":"formula","desc":"Kubernetes CLI"},{"name":"helm","type":"formula","desc":"Kubernetes package manager"},{"name":"k9s","type":"formula","desc":"Kubernetes TUI"},{"name":"awscli","type":"formula","desc":"AWS command line"},{"name":"docker","type":"formula","desc":"Container engine"},{"name":"jq","type":"formula","desc":"JSON processor"},{"name":"yq","type":"formula","desc":"YAML processor"},{"name":"git","type":"formula","desc":"Version control"},{"name":"gh","type":"formula","desc":"GitHub CLI"},{"name":"orbstack","type":"cask","desc":"Docker alternative"},{"name":"lens","type":"cask","desc":"Kubernetes IDE"},{"name":"visual-studio-code","type":"cask","desc":"Code editor"}]', '', 'public', 'platform-eng', '', 0, 1);

-- 14. Data Scientist / ML
INSERT INTO configs (id, user_id, slug, name, description, base_preset, packages, custom_script, visibility, alias, dotfiles_repo, install_count, featured)
VALUES ('ob-seed-data-science', 'openboot-official', 'data-science', 'Data Science / ML', 'Python-first ML workbench with Jupyter, conda environments, and R for statistical analysis.', 'developer', '[{"name":"python","type":"formula","desc":"Python interpreter"},{"name":"uv","type":"formula","desc":"Fast Python package manager"},{"name":"jupyter","type":"formula","desc":"Interactive notebooks"},{"name":"git","type":"formula","desc":"Version control"},{"name":"gh","type":"formula","desc":"GitHub CLI"},{"name":"jq","type":"formula","desc":"JSON processor"},{"name":"wget","type":"formula","desc":"File downloader"},{"name":"htop","type":"formula","desc":"Process viewer"},{"name":"tree","type":"formula","desc":"Directory visualizer"},{"name":"miniconda","type":"cask","desc":"Conda environment manager"},{"name":"visual-studio-code","type":"cask","desc":"Code editor"},{"name":"orbstack","type":"cask","desc":"Docker alternative"},{"name":"rectangle","type":"cask","desc":"Window manager"}]', '', 'public', 'data-science', '', 0, 1);

-- 15. Security Engineer
INSERT INTO configs (id, user_id, slug, name, description, base_preset, packages, custom_script, visibility, alias, dotfiles_repo, install_count, featured)
VALUES ('ob-seed-security-eng', 'openboot-official', 'security-eng', 'Security Engineer', 'Offensive and defensive security toolkit with network scanning, traffic analysis, and encryption tools.', 'developer', '[{"name":"nmap","type":"formula","desc":"Network port scanner"},{"name":"nikto","type":"formula","desc":"Web server scanner"},{"name":"sqlmap","type":"formula","desc":"SQL injection tester"},{"name":"openssl","type":"formula","desc":"Crypto and TLS toolkit"},{"name":"gnupg","type":"formula","desc":"PGP encryption"},{"name":"git","type":"formula","desc":"Version control"},{"name":"gh","type":"formula","desc":"GitHub CLI"},{"name":"jq","type":"formula","desc":"JSON processor"},{"name":"ripgrep","type":"formula","desc":"Fast code search"},{"name":"curl","type":"formula","desc":"HTTP transfer tool"},{"name":"wget","type":"formula","desc":"File downloader"},{"name":"htop","type":"formula","desc":"Process viewer"},{"name":"wireshark","type":"cask","desc":"Packet analyzer"},{"name":"burp-suite","type":"cask","desc":"Web security testing"},{"name":"visual-studio-code","type":"cask","desc":"Code editor"},{"name":"warp","type":"cask","desc":"Modern terminal"}]', '', 'public', 'security-eng', '', 0, 1);

-- 16. Game Dev - Unity
INSERT INTO configs (id, user_id, slug, name, description, base_preset, packages, custom_script, visibility, alias, dotfiles_repo, install_count, featured)
VALUES ('ob-seed-unity-gamedev', 'openboot-official', 'unity-gamedev', 'Game Dev — Unity', 'Unity game development environment with 3D modeling, media processing, and native build tooling.', 'developer', '[{"name":"git","type":"formula","desc":"Version control"},{"name":"cmake","type":"formula","desc":"Cross-platform build system"},{"name":"ffmpeg","type":"formula","desc":"Video/audio processor"},{"name":"imagemagick","type":"formula","desc":"Image processing CLI"},{"name":"gh","type":"formula","desc":"GitHub CLI"},{"name":"tree","type":"formula","desc":"Directory visualizer"},{"name":"jq","type":"formula","desc":"JSON processor"},{"name":"wget","type":"formula","desc":"File downloader"},{"name":"unity-hub","type":"cask","desc":"Unity version manager"},{"name":"blender","type":"cask","desc":"3D modeling and animation"},{"name":"visual-studio-code","type":"cask","desc":"Code editor"},{"name":"obs","type":"cask","desc":"Screen recording"},{"name":"rectangle","type":"cask","desc":"Window manager"}]', '', 'public', 'unity-gamedev', '', 0, 1);

-- 17. Blockchain / Web3
INSERT INTO configs (id, user_id, slug, name, description, base_preset, packages, custom_script, visibility, alias, dotfiles_repo, install_count, featured)
VALUES ('ob-seed-web3-dev', 'openboot-official', 'web3-dev', 'Blockchain / Web3', 'Solidity and smart contract dev stack with Node.js for Hardhat/Foundry and browser wallet testing.', 'developer', '[{"name":"node","type":"formula","desc":"JavaScript runtime"},{"name":"pnpm","type":"formula","desc":"Fast package manager"},{"name":"git","type":"formula","desc":"Version control"},{"name":"gh","type":"formula","desc":"GitHub CLI"},{"name":"jq","type":"formula","desc":"JSON processor"},{"name":"ripgrep","type":"formula","desc":"Fast code search"},{"name":"curl","type":"formula","desc":"HTTP transfer tool"},{"name":"python","type":"formula","desc":"Python interpreter"},{"name":"rustup","type":"formula","desc":"Rust toolchain installer"},{"name":"cmake","type":"formula","desc":"Cross-platform build system"},{"name":"visual-studio-code","type":"cask","desc":"Code editor"},{"name":"google-chrome","type":"cask","desc":"MetaMask browser"},{"name":"orbstack","type":"cask","desc":"Docker alternative"},{"name":"warp","type":"cask","desc":"Modern terminal"}]', '', 'public', 'web3-dev', '', 0, 1);

-- 18. Designer who Codes
INSERT INTO configs (id, user_id, slug, name, description, base_preset, packages, custom_script, visibility, alias, dotfiles_repo, install_count, featured)
VALUES ('ob-seed-design-dev', 'openboot-official', 'design-dev', 'Designer who Codes', 'Design-to-code workflow with Figma, Sketch, screenshot tools, and frontend build essentials.', 'developer', '[{"name":"node","type":"formula","desc":"JavaScript runtime"},{"name":"pnpm","type":"formula","desc":"Fast package manager"},{"name":"imagemagick","type":"formula","desc":"Image processing CLI"},{"name":"ffmpeg","type":"formula","desc":"Video/audio processor"},{"name":"git","type":"formula","desc":"Version control"},{"name":"gh","type":"formula","desc":"GitHub CLI"},{"name":"eza","type":"formula","desc":"Modern ls replacement"},{"name":"bat","type":"formula","desc":"Better cat with syntax"},{"name":"figma","type":"cask","desc":"Design collaboration"},{"name":"sketch","type":"cask","desc":"Vector design tool"},{"name":"visual-studio-code","type":"cask","desc":"Code editor"},{"name":"google-chrome","type":"cask","desc":"Web browser"},{"name":"cleanshot","type":"cask","desc":"Screenshot utility"},{"name":"shottr","type":"cask","desc":"Quick annotation tool"},{"name":"arc","type":"cask","desc":"Productivity browser"},{"name":"rectangle","type":"cask","desc":"Window manager"}]', '', 'public', 'design-dev', '', 0, 1);

-- 19. Student / Beginner
INSERT INTO configs (id, user_id, slug, name, description, base_preset, packages, custom_script, visibility, alias, dotfiles_repo, install_count, featured)
VALUES ('ob-seed-starter-kit', 'openboot-official', 'starter-kit', 'Student / Beginner', 'Everything you need to start coding on Mac — a clean, minimal setup with the tools that matter most.', 'minimal', '[{"name":"git","type":"formula","desc":"Version control"},{"name":"node","type":"formula","desc":"JavaScript runtime"},{"name":"python","type":"formula","desc":"Python interpreter"},{"name":"gh","type":"formula","desc":"GitHub CLI"},{"name":"tree","type":"formula","desc":"Directory visualizer"},{"name":"bat","type":"formula","desc":"Better cat with syntax"},{"name":"fzf","type":"formula","desc":"Fuzzy finder"},{"name":"visual-studio-code","type":"cask","desc":"Code editor"},{"name":"iterm2","type":"cask","desc":"Terminal emulator"},{"name":"google-chrome","type":"cask","desc":"Web browser"},{"name":"rectangle","type":"cask","desc":"Window manager"},{"name":"raycast","type":"cask","desc":"Launcher and productivity"}]', '', 'public', 'starter-kit', '', 0, 1);

-- 20. Content Creator / Tech Writer
INSERT INTO configs (id, user_id, slug, name, description, base_preset, packages, custom_script, visibility, alias, dotfiles_repo, install_count, featured)
VALUES ('ob-seed-tech-writer', 'openboot-official', 'tech-writer', 'Content Creator / Tech Writer', 'Technical writing and content creation suite with static sites, document conversion, and recording tools.', 'developer', '[{"name":"hugo","type":"formula","desc":"Static site generator"},{"name":"pandoc","type":"formula","desc":"Document converter"},{"name":"asciinema","type":"formula","desc":"Terminal recorder"},{"name":"ffmpeg","type":"formula","desc":"Video/audio processor"},{"name":"imagemagick","type":"formula","desc":"Image processing CLI"},{"name":"git","type":"formula","desc":"Version control"},{"name":"gh","type":"formula","desc":"GitHub CLI"},{"name":"tree","type":"formula","desc":"Directory visualizer"},{"name":"bat","type":"formula","desc":"Better cat with syntax"},{"name":"eza","type":"formula","desc":"Modern ls replacement"},{"name":"obs","type":"cask","desc":"Screen recording"},{"name":"visual-studio-code","type":"cask","desc":"Code editor"},{"name":"cleanshot","type":"cask","desc":"Screenshot utility"},{"name":"notion","type":"cask","desc":"Notes and docs"}]', '', 'public', 'tech-writer', '', 0, 1);
