-- Enrich config packages to be more realistic
-- Real developers use 30-60 tools, not just 10-15

-- 1. Frontend - React (was: 15 packages → enriched to: 42 packages)
UPDATE configs SET packages = '[
  {"name":"node","type":"formula","desc":"JavaScript runtime"},
  {"name":"pnpm","type":"formula","desc":"Fast package manager"},
  {"name":"bun","type":"formula","desc":"Fast JS runtime & bundler"},
  {"name":"watchman","type":"formula","desc":"File watcher for React"},
  {"name":"typescript","type":"formula","desc":"Typed JavaScript compiler"},
  {"name":"git","type":"formula","desc":"Version control"},
  {"name":"gh","type":"formula","desc":"GitHub CLI"},
  {"name":"eza","type":"formula","desc":"Modern ls replacement"},
  {"name":"fzf","type":"formula","desc":"Fuzzy finder"},
  {"name":"ripgrep","type":"formula","desc":"Fast code search"},
  {"name":"bat","type":"formula","desc":"Better cat with syntax"},
  {"name":"jq","type":"formula","desc":"JSON processor"},
  {"name":"httpie","type":"formula","desc":"HTTP client for APIs"},
  {"name":"lazygit","type":"formula","desc":"Git TUI"},
  {"name":"tmux","type":"formula","desc":"Terminal multiplexer"},
  {"name":"tree","type":"formula","desc":"Directory visualizer"},
  {"name":"fd","type":"formula","desc":"Fast file finder"},
  {"name":"delta","type":"formula","desc":"Git diff with colors"},
  {"name":"gh-dash","type":"formula","desc":"GitHub dashboard TUI"},
  {"name":"glow","type":"formula","desc":"Markdown reader in terminal"},
  {"name":"tldr","type":"formula","desc":"Simplified man pages"},
  {"name":"ncdu","type":"formula","desc":"Disk usage analyzer"},
  {"name":"htop","type":"formula","desc":"Process viewer"},
  {"name":"curl","type":"formula","desc":"HTTP transfer tool"},
  {"name":"wget","type":"formula","desc":"File downloader"},
  {"name":"imagemagick","type":"formula","desc":"Image processing CLI"},
  {"name":"ffmpeg","type":"formula","desc":"Video processing"},
  {"name":"visual-studio-code","type":"cask","desc":"Code editor"},
  {"name":"google-chrome","type":"cask","desc":"Web browser"},
  {"name":"firefox","type":"cask","desc":"Testing browser"},
  {"name":"arc","type":"cask","desc":"Productivity browser"},
  {"name":"figma","type":"cask","desc":"Design collaboration"},
  {"name":"iterm2","type":"cask","desc":"Terminal emulator"},
  {"name":"warp","type":"cask","desc":"Modern terminal"},
  {"name":"rectangle","type":"cask","desc":"Window manager"},
  {"name":"raycast","type":"cask","desc":"Launcher and productivity"},
  {"name":"cleanshot","type":"cask","desc":"Screenshot utility"},
  {"name":"postman","type":"cask","desc":"API testing"},
  {"name":"slack","type":"cask","desc":"Team communication"},
  {"name":"discord","type":"cask","desc":"Developer community"},
  {"name":"notion","type":"cask","desc":"Notes and docs"},
  {"name":"1password","type":"cask","desc":"Password manager"}
]' WHERE id = 'ob-seed-react-frontend';

-- 2. Frontend - Vue (was: 14 packages → enriched to: 38 packages)
UPDATE configs SET packages = '[
  {"name":"node","type":"formula","desc":"JavaScript runtime"},
  {"name":"pnpm","type":"formula","desc":"Fast package manager"},
  {"name":"deno","type":"formula","desc":"Secure JS/TS runtime"},
  {"name":"bun","type":"formula","desc":"Fast JS runtime & bundler"},
  {"name":"git","type":"formula","desc":"Version control"},
  {"name":"gh","type":"formula","desc":"GitHub CLI"},
  {"name":"jq","type":"formula","desc":"JSON processor"},
  {"name":"eza","type":"formula","desc":"Modern ls replacement"},
  {"name":"fzf","type":"formula","desc":"Fuzzy finder"},
  {"name":"bat","type":"formula","desc":"Better cat with syntax"},
  {"name":"ripgrep","type":"formula","desc":"Fast code search"},
  {"name":"fd","type":"formula","desc":"Fast file finder"},
  {"name":"httpie","type":"formula","desc":"HTTP client for APIs"},
  {"name":"lazygit","type":"formula","desc":"Git TUI"},
  {"name":"delta","type":"formula","desc":"Git diff with colors"},
  {"name":"tmux","type":"formula","desc":"Terminal multiplexer"},
  {"name":"tree","type":"formula","desc":"Directory visualizer"},
  {"name":"tldr","type":"formula","desc":"Simplified man pages"},
  {"name":"glow","type":"formula","desc":"Markdown reader"},
  {"name":"htop","type":"formula","desc":"Process viewer"},
  {"name":"curl","type":"formula","desc":"HTTP transfer tool"},
  {"name":"imagemagick","type":"formula","desc":"Image processing"},
  {"name":"visual-studio-code","type":"cask","desc":"Code editor"},
  {"name":"google-chrome","type":"cask","desc":"Web browser"},
  {"name":"firefox","type":"cask","desc":"Testing browser"},
  {"name":"arc","type":"cask","desc":"Productivity browser"},
  {"name":"figma","type":"cask","desc":"Design collaboration"},
  {"name":"warp","type":"cask","desc":"Modern terminal"},
  {"name":"iterm2","type":"cask","desc":"Terminal emulator"},
  {"name":"rectangle","type":"cask","desc":"Window manager"},
  {"name":"raycast","type":"cask","desc":"Launcher and productivity"},
  {"name":"postman","type":"cask","desc":"API testing"},
  {"name":"cleanshot","type":"cask","desc":"Screenshot utility"},
  {"name":"slack","type":"cask","desc":"Team communication"},
  {"name":"discord","type":"cask","desc":"Developer community"},
  {"name":"notion","type":"cask","desc":"Notes and docs"},
  {"name":"obsidian","type":"cask","desc":"Knowledge base"},
  {"name":"1password","type":"cask","desc":"Password manager"}
]' WHERE id = 'ob-seed-vue-frontend';

-- 3. Backend - Go (was: 13 packages → enriched to: 45 packages)
UPDATE configs SET packages = '[
  {"name":"go","type":"formula","desc":"Go programming language"},
  {"name":"golangci-lint","type":"formula","desc":"Go linter aggregator"},
  {"name":"delve","type":"formula","desc":"Go debugger"},
  {"name":"protobuf","type":"formula","desc":"Protocol buffer compiler"},
  {"name":"protoc-gen-go","type":"formula","desc":"Go protoc plugin"},
  {"name":"grpcurl","type":"formula","desc":"gRPC curl client"},
  {"name":"evans","type":"formula","desc":"gRPC client TUI"},
  {"name":"air","type":"formula","desc":"Live reload for Go"},
  {"name":"postgresql","type":"formula","desc":"Relational database"},
  {"name":"redis","type":"formula","desc":"In-memory data store"},
  {"name":"git","type":"formula","desc":"Version control"},
  {"name":"gh","type":"formula","desc":"GitHub CLI"},
  {"name":"jq","type":"formula","desc":"JSON processor"},
  {"name":"yq","type":"formula","desc":"YAML processor"},
  {"name":"ripgrep","type":"formula","desc":"Fast code search"},
  {"name":"lazygit","type":"formula","desc":"Git TUI"},
  {"name":"httpie","type":"formula","desc":"HTTP client for APIs"},
  {"name":"curl","type":"formula","desc":"HTTP transfer tool"},
  {"name":"wget","type":"formula","desc":"File downloader"},
  {"name":"tmux","type":"formula","desc":"Terminal multiplexer"},
  {"name":"tree","type":"formula","desc":"Directory visualizer"},
  {"name":"fd","type":"formula","desc":"Fast file finder"},
  {"name":"bat","type":"formula","desc":"Better cat with syntax"},
  {"name":"eza","type":"formula","desc":"Modern ls replacement"},
  {"name":"delta","type":"formula","desc":"Git diff with colors"},
  {"name":"btop","type":"formula","desc":"Resource monitor"},
  {"name":"htop","type":"formula","desc":"Process viewer"},
  {"name":"ncdu","type":"formula","desc":"Disk usage analyzer"},
  {"name":"tldr","type":"formula","desc":"Simplified man pages"},
  {"name":"glow","type":"formula","desc":"Markdown reader"},
  {"name":"fzf","type":"formula","desc":"Fuzzy finder"},
  {"name":"watch","type":"formula","desc":"Execute program periodically"},
  {"name":"visual-studio-code","type":"cask","desc":"Code editor"},
  {"name":"goland","type":"cask","desc":"Go IDE"},
  {"name":"tableplus","type":"cask","desc":"Database GUI"},
  {"name":"redisinsight","type":"cask","desc":"Redis GUI"},
  {"name":"orbstack","type":"cask","desc":"Docker alternative"},
  {"name":"postman","type":"cask","desc":"API testing"},
  {"name":"warp","type":"cask","desc":"Modern terminal"},
  {"name":"iterm2","type":"cask","desc":"Terminal emulator"},
  {"name":"rectangle","type":"cask","desc":"Window manager"},
  {"name":"raycast","type":"cask","desc":"Launcher and productivity"},
  {"name":"slack","type":"cask","desc":"Team communication"},
  {"name":"notion","type":"cask","desc":"Notes and docs"},
  {"name":"1password","type":"cask","desc":"Password manager"}
]' WHERE id = 'ob-seed-go-backend';

-- 4. Backend - Python (was: 14 packages → enriched to: 48 packages)
UPDATE configs SET packages = '[
  {"name":"python","type":"formula","desc":"Python interpreter"},
  {"name":"python@3.11","type":"formula","desc":"Python 3.11 LTS"},
  {"name":"uv","type":"formula","desc":"Fast Python package manager"},
  {"name":"ruff","type":"formula","desc":"Extremely fast linter"},
  {"name":"pipx","type":"formula","desc":"Isolated CLI installs"},
  {"name":"pyenv","type":"formula","desc":"Python version manager"},
  {"name":"postgresql","type":"formula","desc":"Relational database"},
  {"name":"redis","type":"formula","desc":"In-memory data store"},
  {"name":"rabbitmq","type":"formula","desc":"Message broker"},
  {"name":"httpie","type":"formula","desc":"HTTP client for APIs"},
  {"name":"git","type":"formula","desc":"Version control"},
  {"name":"gh","type":"formula","desc":"GitHub CLI"},
  {"name":"jq","type":"formula","desc":"JSON processor"},
  {"name":"yq","type":"formula","desc":"YAML processor"},
  {"name":"ripgrep","type":"formula","desc":"Fast code search"},
  {"name":"lazygit","type":"formula","desc":"Git TUI"},
  {"name":"tmux","type":"formula","desc":"Terminal multiplexer"},
  {"name":"tree","type":"formula","desc":"Directory visualizer"},
  {"name":"fd","type":"formula","desc":"Fast file finder"},
  {"name":"bat","type":"formula","desc":"Better cat with syntax"},
  {"name":"eza","type":"formula","desc":"Modern ls replacement"},
  {"name":"delta","type":"formula","desc":"Git diff with colors"},
  {"name":"htop","type":"formula","desc":"Process viewer"},
  {"name":"btop","type":"formula","desc":"Resource monitor"},
  {"name":"ncdu","type":"formula","desc":"Disk usage analyzer"},
  {"name":"tldr","type":"formula","desc":"Simplified man pages"},
  {"name":"glow","type":"formula","desc":"Markdown reader"},
  {"name":"fzf","type":"formula","desc":"Fuzzy finder"},
  {"name":"curl","type":"formula","desc":"HTTP transfer tool"},
  {"name":"wget","type":"formula","desc":"File downloader"},
  {"name":"graphviz","type":"formula","desc":"Graph visualization"},
  {"name":"imagemagick","type":"formula","desc":"Image processing"},
  {"name":"cursor","type":"cask","desc":"AI-powered code editor"},
  {"name":"visual-studio-code","type":"cask","desc":"Code editor"},
  {"name":"pycharm","type":"cask","desc":"Python IDE"},
  {"name":"tableplus","type":"cask","desc":"Database GUI"},
  {"name":"redisinsight","type":"cask","desc":"Redis GUI"},
  {"name":"orbstack","type":"cask","desc":"Docker alternative"},
  {"name":"postman","type":"cask","desc":"API testing"},
  {"name":"warp","type":"cask","desc":"Modern terminal"},
  {"name":"iterm2","type":"cask","desc":"Terminal emulator"},
  {"name":"rectangle","type":"cask","desc":"Window manager"},
  {"name":"raycast","type":"cask","desc":"Launcher and productivity"},
  {"name":"slack","type":"cask","desc":"Team communication"},
  {"name":"discord","type":"cask","desc":"Developer community"},
  {"name":"notion","type":"cask","desc":"Notes and docs"},
  {"name":"obsidian","type":"cask","desc":"Knowledge base"},
  {"name":"1password","type":"cask","desc":"Password manager"}
]' WHERE id = 'ob-seed-python-backend';

-- 5. Backend - Node.js (was: 14 packages → enriched to: 46 packages)
UPDATE configs SET packages = '[
  {"name":"node","type":"formula","desc":"JavaScript runtime"},
  {"name":"node@20","type":"formula","desc":"Node.js LTS 20"},
  {"name":"pnpm","type":"formula","desc":"Fast package manager"},
  {"name":"bun","type":"formula","desc":"Fast JS runtime"},
  {"name":"redis","type":"formula","desc":"In-memory data store"},
  {"name":"postgresql","type":"formula","desc":"Relational database"},
  {"name":"mongodb-community","type":"formula","desc":"Document database"},
  {"name":"rabbitmq","type":"formula","desc":"Message broker"},
  {"name":"git","type":"formula","desc":"Version control"},
  {"name":"gh","type":"formula","desc":"GitHub CLI"},
  {"name":"jq","type":"formula","desc":"JSON processor"},
  {"name":"yq","type":"formula","desc":"YAML processor"},
  {"name":"httpie","type":"formula","desc":"HTTP client for APIs"},
  {"name":"lazygit","type":"formula","desc":"Git TUI"},
  {"name":"ripgrep","type":"formula","desc":"Fast code search"},
  {"name":"fd","type":"formula","desc":"Fast file finder"},
  {"name":"bat","type":"formula","desc":"Better cat with syntax"},
  {"name":"eza","type":"formula","desc":"Modern ls replacement"},
  {"name":"delta","type":"formula","desc":"Git diff with colors"},
  {"name":"tmux","type":"formula","desc":"Terminal multiplexer"},
  {"name":"tree","type":"formula","desc":"Directory visualizer"},
  {"name":"htop","type":"formula","desc":"Process viewer"},
  {"name":"btop","type":"formula","desc":"Resource monitor"},
  {"name":"ncdu","type":"formula","desc":"Disk usage analyzer"},
  {"name":"tldr","type":"formula","desc":"Simplified man pages"},
  {"name":"glow","type":"formula","desc":"Markdown reader"},
  {"name":"fzf","type":"formula","desc":"Fuzzy finder"},
  {"name":"curl","type":"formula","desc":"HTTP transfer tool"},
  {"name":"wget","type":"formula","desc":"File downloader"},
  {"name":"watchman","type":"formula","desc":"File watcher"},
  {"name":"visual-studio-code","type":"cask","desc":"Code editor"},
  {"name":"webstorm","type":"cask","desc":"JavaScript IDE"},
  {"name":"postman","type":"cask","desc":"API testing platform"},
  {"name":"insomnia","type":"cask","desc":"API client"},
  {"name":"tableplus","type":"cask","desc":"Database GUI"},
  {"name":"mongodb-compass","type":"cask","desc":"MongoDB GUI"},
  {"name":"redisinsight","type":"cask","desc":"Redis GUI"},
  {"name":"orbstack","type":"cask","desc":"Docker alternative"},
  {"name":"warp","type":"cask","desc":"Modern terminal"},
  {"name":"iterm2","type":"cask","desc":"Terminal emulator"},
  {"name":"rectangle","type":"cask","desc":"Window manager"},
  {"name":"raycast","type":"cask","desc":"Launcher and productivity"},
  {"name":"slack","type":"cask","desc":"Team communication"},
  {"name":"discord","type":"cask","desc":"Developer community"},
  {"name":"notion","type":"cask","desc":"Notes and docs"},
  {"name":"1password","type":"cask","desc":"Password manager"}
]' WHERE id = 'ob-seed-nodejs-backend';

-- 6. Backend - Java/Spring (was: 13 packages → enriched to: 41 packages)
UPDATE configs SET packages = '[
  {"name":"openjdk","type":"formula","desc":"Java development kit"},
  {"name":"openjdk@17","type":"formula","desc":"Java 17 LTS"},
  {"name":"maven","type":"formula","desc":"Java build tool"},
  {"name":"gradle","type":"formula","desc":"Flexible build automation"},
  {"name":"postgresql","type":"formula","desc":"Relational database"},
  {"name":"redis","type":"formula","desc":"In-memory data store"},
  {"name":"kafka","type":"formula","desc":"Stream processing"},
  {"name":"git","type":"formula","desc":"Version control"},
  {"name":"gh","type":"formula","desc":"GitHub CLI"},
  {"name":"jq","type":"formula","desc":"JSON processor"},
  {"name":"yq","type":"formula","desc":"YAML processor"},
  {"name":"httpie","type":"formula","desc":"HTTP client for APIs"},
  {"name":"ripgrep","type":"formula","desc":"Fast code search"},
  {"name":"lazygit","type":"formula","desc":"Git TUI"},
  {"name":"fd","type":"formula","desc":"Fast file finder"},
  {"name":"bat","type":"formula","desc":"Better cat with syntax"},
  {"name":"eza","type":"formula","desc":"Modern ls replacement"},
  {"name":"delta","type":"formula","desc":"Git diff with colors"},
  {"name":"tmux","type":"formula","desc":"Terminal multiplexer"},
  {"name":"tree","type":"formula","desc":"Directory visualizer"},
  {"name":"btop","type":"formula","desc":"System resource monitor"},
  {"name":"htop","type":"formula","desc":"Process viewer"},
  {"name":"ncdu","type":"formula","desc":"Disk usage analyzer"},
  {"name":"tldr","type":"formula","desc":"Simplified man pages"},
  {"name":"glow","type":"formula","desc":"Markdown reader"},
  {"name":"fzf","type":"formula","desc":"Fuzzy finder"},
  {"name":"curl","type":"formula","desc":"HTTP transfer tool"},
  {"name":"wget","type":"formula","desc":"File downloader"},
  {"name":"jetbrains-toolbox","type":"cask","desc":"JetBrains IDE manager"},
  {"name":"intellij-idea","type":"cask","desc":"Java IDE"},
  {"name":"visual-studio-code","type":"cask","desc":"Code editor"},
  {"name":"tableplus","type":"cask","desc":"Database GUI"},
  {"name":"redisinsight","type":"cask","desc":"Redis GUI"},
  {"name":"orbstack","type":"cask","desc":"Docker alternative"},
  {"name":"postman","type":"cask","desc":"API testing platform"},
  {"name":"warp","type":"cask","desc":"Modern terminal"},
  {"name":"rectangle","type":"cask","desc":"Window manager"},
  {"name":"raycast","type":"cask","desc":"Launcher and productivity"},
  {"name":"slack","type":"cask","desc":"Team communication"},
  {"name":"notion","type":"cask","desc":"Notes and docs"},
  {"name":"1password","type":"cask","desc":"Password manager"}
]' WHERE id = 'ob-seed-java-spring';

-- 7. Backend - Rust (was: 13 packages → enriched to: 43 packages)
UPDATE configs SET packages = '[
  {"name":"rustup","type":"formula","desc":"Rust toolchain installer"},
  {"name":"cmake","type":"formula","desc":"Cross-platform build system"},
  {"name":"protobuf","type":"formula","desc":"Protocol buffer compiler"},
  {"name":"postgresql","type":"formula","desc":"Relational database"},
  {"name":"redis","type":"formula","desc":"In-memory data store"},
  {"name":"git","type":"formula","desc":"Version control"},
  {"name":"gh","type":"formula","desc":"GitHub CLI"},
  {"name":"jq","type":"formula","desc":"JSON processor"},
  {"name":"yq","type":"formula","desc":"YAML processor"},
  {"name":"httpie","type":"formula","desc":"HTTP client for APIs"},
  {"name":"ripgrep","type":"formula","desc":"Fast code search"},
  {"name":"fd","type":"formula","desc":"Fast file finder"},
  {"name":"bat","type":"formula","desc":"Better cat with syntax"},
  {"name":"eza","type":"formula","desc":"Modern ls replacement"},
  {"name":"delta","type":"formula","desc":"Git diff with colors"},
  {"name":"lazygit","type":"formula","desc":"Git TUI"},
  {"name":"tmux","type":"formula","desc":"Terminal multiplexer"},
  {"name":"tree","type":"formula","desc":"Directory visualizer"},
  {"name":"htop","type":"formula","desc":"Process viewer"},
  {"name":"btop","type":"formula","desc":"Resource monitor"},
  {"name":"ncdu","type":"formula","desc":"Disk usage analyzer"},
  {"name":"tldr","type":"formula","desc":"Simplified man pages"},
  {"name":"glow","type":"formula","desc":"Markdown reader"},
  {"name":"fzf","type":"formula","desc":"Fuzzy finder"},
  {"name":"zoxide","type":"formula","desc":"Smarter cd command"},
  {"name":"starship","type":"formula","desc":"Shell prompt"},
  {"name":"curl","type":"formula","desc":"HTTP transfer tool"},
  {"name":"wget","type":"formula","desc":"File downloader"},
  {"name":"openssl","type":"formula","desc":"SSL/TLS toolkit"},
  {"name":"visual-studio-code","type":"cask","desc":"Code editor"},
  {"name":"rust-rover","type":"cask","desc":"Rust IDE"},
  {"name":"tableplus","type":"cask","desc":"Database GUI"},
  {"name":"redisinsight","type":"cask","desc":"Redis GUI"},
  {"name":"orbstack","type":"cask","desc":"Docker alternative"},
  {"name":"postman","type":"cask","desc":"API testing"},
  {"name":"warp","type":"cask","desc":"Modern terminal"},
  {"name":"iterm2","type":"cask","desc":"Terminal emulator"},
  {"name":"rectangle","type":"cask","desc":"Window manager"},
  {"name":"raycast","type":"cask","desc":"Launcher and productivity"},
  {"name":"slack","type":"cask","desc":"Team communication"},
  {"name":"discord","type":"cask","desc":"Developer community"},
  {"name":"notion","type":"cask","desc":"Notes and docs"},
  {"name":"1password","type":"cask","desc":"Password manager"}
]' WHERE id = 'ob-seed-rust-backend';

-- 8. Backend - Ruby on Rails (was: 13 packages → enriched to: 40 packages)
UPDATE configs SET packages = '[
  {"name":"ruby","type":"formula","desc":"Ruby language"},
  {"name":"rbenv","type":"formula","desc":"Ruby version manager"},
  {"name":"ruby-build","type":"formula","desc":"rbenv plugin for building"},
  {"name":"postgresql","type":"formula","desc":"Relational database"},
  {"name":"redis","type":"formula","desc":"In-memory data store"},
  {"name":"overmind","type":"formula","desc":"Procfile process manager"},
  {"name":"git","type":"formula","desc":"Version control"},
  {"name":"gh","type":"formula","desc":"GitHub CLI"},
  {"name":"imagemagick","type":"formula","desc":"Image processing CLI"},
  {"name":"libvips","type":"formula","desc":"Image processing library"},
  {"name":"jq","type":"formula","desc":"JSON processor"},
  {"name":"yq","type":"formula","desc":"YAML processor"},
  {"name":"httpie","type":"formula","desc":"HTTP client for APIs"},
  {"name":"lazygit","type":"formula","desc":"Git TUI"},
  {"name":"ripgrep","type":"formula","desc":"Fast code search"},
  {"name":"fd","type":"formula","desc":"Fast file finder"},
  {"name":"bat","type":"formula","desc":"Better cat with syntax"},
  {"name":"eza","type":"formula","desc":"Modern ls replacement"},
  {"name":"delta","type":"formula","desc":"Git diff with colors"},
  {"name":"tmux","type":"formula","desc":"Terminal multiplexer"},
  {"name":"tree","type":"formula","desc":"Directory visualizer"},
  {"name":"htop","type":"formula","desc":"Process viewer"},
  {"name":"ncdu","type":"formula","desc":"Disk usage analyzer"},
  {"name":"tldr","type":"formula","desc":"Simplified man pages"},
  {"name":"glow","type":"formula","desc":"Markdown reader"},
  {"name":"fzf","type":"formula","desc":"Fuzzy finder"},
  {"name":"curl","type":"formula","desc":"HTTP transfer tool"},
  {"name":"wget","type":"formula","desc":"File downloader"},
  {"name":"visual-studio-code","type":"cask","desc":"Code editor"},
  {"name":"rubymine","type":"cask","desc":"Ruby IDE"},
  {"name":"tableplus","type":"cask","desc":"Database GUI"},
  {"name":"redisinsight","type":"cask","desc":"Redis GUI"},
  {"name":"orbstack","type":"cask","desc":"Docker alternative"},
  {"name":"postman","type":"cask","desc":"API testing"},
  {"name":"warp","type":"cask","desc":"Modern terminal"},
  {"name":"rectangle","type":"cask","desc":"Window manager"},
  {"name":"raycast","type":"cask","desc":"Launcher and productivity"},
  {"name":"slack","type":"cask","desc":"Team communication"},
  {"name":"notion","type":"cask","desc":"Notes and docs"},
  {"name":"1password","type":"cask","desc":"Password manager"}
]' WHERE id = 'ob-seed-rails-backend';

-- 9. Full-Stack T3 (was: 15 packages → enriched to: 52 packages)
UPDATE configs SET packages = '[
  {"name":"node","type":"formula","desc":"JavaScript runtime"},
  {"name":"pnpm","type":"formula","desc":"Fast package manager"},
  {"name":"bun","type":"formula","desc":"Fast JS runtime"},
  {"name":"postgresql","type":"formula","desc":"Relational database"},
  {"name":"redis","type":"formula","desc":"In-memory data store"},
  {"name":"git","type":"formula","desc":"Version control"},
  {"name":"gh","type":"formula","desc":"GitHub CLI"},
  {"name":"typescript","type":"formula","desc":"Typed JavaScript compiler"},
  {"name":"jq","type":"formula","desc":"JSON processor"},
  {"name":"yq","type":"formula","desc":"YAML processor"},
  {"name":"httpie","type":"formula","desc":"HTTP client for APIs"},
  {"name":"lazygit","type":"formula","desc":"Git TUI"},
  {"name":"ripgrep","type":"formula","desc":"Fast code search"},
  {"name":"fd","type":"formula","desc":"Fast file finder"},
  {"name":"bat","type":"formula","desc":"Better cat with syntax"},
  {"name":"eza","type":"formula","desc":"Modern ls replacement"},
  {"name":"delta","type":"formula","desc":"Git diff with colors"},
  {"name":"tmux","type":"formula","desc":"Terminal multiplexer"},
  {"name":"tree","type":"formula","desc":"Directory visualizer"},
  {"name":"fzf","type":"formula","desc":"Fuzzy finder"},
  {"name":"htop","type":"formula","desc":"Process viewer"},
  {"name":"btop","type":"formula","desc":"Resource monitor"},
  {"name":"ncdu","type":"formula","desc":"Disk usage analyzer"},
  {"name":"tldr","type":"formula","desc":"Simplified man pages"},
  {"name":"glow","type":"formula","desc":"Markdown reader"},
  {"name":"curl","type":"formula","desc":"HTTP transfer tool"},
  {"name":"wget","type":"formula","desc":"File downloader"},
  {"name":"watchman","type":"formula","desc":"File watcher"},
  {"name":"imagemagick","type":"formula","desc":"Image processing"},
  {"name":"ffmpeg","type":"formula","desc":"Video processing"},
  {"name":"visual-studio-code","type":"cask","desc":"Code editor"},
  {"name":"cursor","type":"cask","desc":"AI code editor"},
  {"name":"google-chrome","type":"cask","desc":"Web browser"},
  {"name":"arc","type":"cask","desc":"Productivity browser"},
  {"name":"firefox","type":"cask","desc":"Testing browser"},
  {"name":"figma","type":"cask","desc":"Design collaboration"},
  {"name":"tableplus","type":"cask","desc":"Database GUI"},
  {"name":"redisinsight","type":"cask","desc":"Redis GUI"},
  {"name":"orbstack","type":"cask","desc":"Docker alternative"},
  {"name":"postman","type":"cask","desc":"API testing"},
  {"name":"insomnia","type":"cask","desc":"API client"},
  {"name":"warp","type":"cask","desc":"Modern terminal"},
  {"name":"iterm2","type":"cask","desc":"Terminal emulator"},
  {"name":"rectangle","type":"cask","desc":"Window manager"},
  {"name":"raycast","type":"cask","desc":"Launcher and productivity"},
  {"name":"cleanshot","type":"cask","desc":"Screenshot utility"},
  {"name":"slack","type":"cask","desc":"Team communication"},
  {"name":"discord","type":"cask","desc":"Developer community"},
  {"name":"zoom","type":"cask","desc":"Video conferencing"},
  {"name":"notion","type":"cask","desc":"Notes and docs"},
  {"name":"obsidian","type":"cask","desc":"Knowledge base"},
  {"name":"1password","type":"cask","desc":"Password manager"}
]' WHERE id = 'ob-seed-t3-fullstack';

-- 10. iOS/macOS Developer (was: 13 packages → enriched to: 38 packages)
UPDATE configs SET packages = '[
  {"name":"swiftlint","type":"formula","desc":"Swift style enforcer"},
  {"name":"swiftformat","type":"formula","desc":"Swift code formatter"},
  {"name":"cocoapods","type":"formula","desc":"iOS dependency manager"},
  {"name":"fastlane","type":"formula","desc":"iOS CI/CD automation"},
  {"name":"xcbeautify","type":"formula","desc":"Xcode build formatter"},
  {"name":"xcodegen","type":"formula","desc":"Xcode project generator"},
  {"name":"mint","type":"formula","desc":"Swift package installer"},
  {"name":"git","type":"formula","desc":"Version control"},
  {"name":"gh","type":"formula","desc":"GitHub CLI"},
  {"name":"ripgrep","type":"formula","desc":"Fast code search"},
  {"name":"jq","type":"formula","desc":"JSON processor"},
  {"name":"tree","type":"formula","desc":"Directory visualizer"},
  {"name":"lazygit","type":"formula","desc":"Git TUI"},
  {"name":"fd","type":"formula","desc":"Fast file finder"},
  {"name":"bat","type":"formula","desc":"Better cat with syntax"},
  {"name":"eza","type":"formula","desc":"Modern ls replacement"},
  {"name":"delta","type":"formula","desc":"Git diff with colors"},
  {"name":"fzf","type":"formula","desc":"Fuzzy finder"},
  {"name":"tldr","type":"formula","desc":"Simplified man pages"},
  {"name":"htop","type":"formula","desc":"Process viewer"},
  {"name":"curl","type":"formula","desc":"HTTP transfer tool"},
  {"name":"wget","type":"formula","desc":"File downloader"},
  {"name":"sf-symbols","type":"cask","desc":"Apple icon browser"},
  {"name":"proxyman","type":"cask","desc":"HTTP debugging proxy"},
  {"name":"charles","type":"cask","desc":"Network traffic analyzer"},
  {"name":"visual-studio-code","type":"cask","desc":"Code editor"},
  {"name":"figma","type":"cask","desc":"Design collaboration"},
  {"name":"simulator","type":"cask","desc":"iOS simulator standalone"},
  {"name":"warp","type":"cask","desc":"Modern terminal"},
  {"name":"iterm2","type":"cask","desc":"Terminal emulator"},
  {"name":"rectangle","type":"cask","desc":"Window manager"},
  {"name":"raycast","type":"cask","desc":"Launcher and productivity"},
  {"name":"slack","type":"cask","desc":"Team communication"},
  {"name":"discord","type":"cask","desc":"Developer community"},
  {"name":"testflight","type":"cask","desc":"App testing platform"},
  {"name":"notion","type":"cask","desc":"Notes and docs"},
  {"name":"1password","type":"cask","desc":"Password manager"}
]' WHERE id = 'ob-seed-ios-developer';

-- 11. Android Developer (was: 13 packages → enriched to: 37 packages)
UPDATE configs SET packages = '[
  {"name":"openjdk","type":"formula","desc":"Java development kit"},
  {"name":"openjdk@17","type":"formula","desc":"Java 17 LTS"},
  {"name":"gradle","type":"formula","desc":"Flexible build automation"},
  {"name":"scrcpy","type":"formula","desc":"Android screen mirror"},
  {"name":"adb","type":"formula","desc":"Android debug bridge"},
  {"name":"git","type":"formula","desc":"Version control"},
  {"name":"gh","type":"formula","desc":"GitHub CLI"},
  {"name":"jq","type":"formula","desc":"JSON processor"},
  {"name":"ripgrep","type":"formula","desc":"Fast code search"},
  {"name":"tree","type":"formula","desc":"Directory visualizer"},
  {"name":"lazygit","type":"formula","desc":"Git TUI"},
  {"name":"fd","type":"formula","desc":"Fast file finder"},
  {"name":"bat","type":"formula","desc":"Better cat with syntax"},
  {"name":"eza","type":"formula","desc":"Modern ls replacement"},
  {"name":"delta","type":"formula","desc":"Git diff with colors"},
  {"name":"btop","type":"formula","desc":"System resource monitor"},
  {"name":"htop","type":"formula","desc":"Process viewer"},
  {"name":"fzf","type":"formula","desc":"Fuzzy finder"},
  {"name":"tldr","type":"formula","desc":"Simplified man pages"},
  {"name":"curl","type":"formula","desc":"HTTP transfer tool"},
  {"name":"wget","type":"formula","desc":"File downloader"},
  {"name":"android-studio","type":"cask","desc":"Android IDE"},
  {"name":"visual-studio-code","type":"cask","desc":"Code editor"},
  {"name":"figma","type":"cask","desc":"Design collaboration"},
  {"name":"genymotion","type":"cask","desc":"Android emulator"},
  {"name":"charles","type":"cask","desc":"Network debugger"},
  {"name":"postman","type":"cask","desc":"API testing"},
  {"name":"warp","type":"cask","desc":"Modern terminal"},
  {"name":"iterm2","type":"cask","desc":"Terminal emulator"},
  {"name":"rectangle","type":"cask","desc":"Window manager"},
  {"name":"raycast","type":"cask","desc":"Launcher and productivity"},
  {"name":"slack","type":"cask","desc":"Team communication"},
  {"name":"discord","type":"cask","desc":"Developer community"},
  {"name":"zoom","type":"cask","desc":"Video conferencing"},
  {"name":"notion","type":"cask","desc":"Notes and docs"},
  {"name":"1password","type":"cask","desc":"Password manager"}
]' WHERE id = 'ob-seed-android-dev';

-- 12. DevOps / SRE (was: 16 packages → enriched to: 55 packages)
UPDATE configs SET packages = '[
  {"name":"terraform","type":"formula","desc":"Infrastructure as code"},
  {"name":"kubectl","type":"formula","desc":"Kubernetes CLI"},
  {"name":"helm","type":"formula","desc":"Kubernetes package manager"},
  {"name":"k9s","type":"formula","desc":"Kubernetes TUI"},
  {"name":"kubectx","type":"formula","desc":"Kubernetes context switcher"},
  {"name":"kustomize","type":"formula","desc":"Kubernetes config customizer"},
  {"name":"awscli","type":"formula","desc":"AWS command line"},
  {"name":"aws-sam-cli","type":"formula","desc":"AWS Serverless toolkit"},
  {"name":"eksctl","type":"formula","desc":"EKS cluster manager"},
  {"name":"docker","type":"formula","desc":"Container engine"},
  {"name":"docker-compose","type":"formula","desc":"Multi-container apps"},
  {"name":"ansible","type":"formula","desc":"Configuration management"},
  {"name":"packer","type":"formula","desc":"Image builder"},
  {"name":"vault","type":"formula","desc":"Secret management"},
  {"name":"consul","type":"formula","desc":"Service mesh"},
  {"name":"prometheus","type":"formula","desc":"Monitoring system"},
  {"name":"grafana","type":"formula","desc":"Metrics visualization"},
  {"name":"jq","type":"formula","desc":"JSON processor"},
  {"name":"yq","type":"formula","desc":"YAML processor"},
  {"name":"git","type":"formula","desc":"Version control"},
  {"name":"gh","type":"formula","desc":"GitHub CLI"},
  {"name":"ripgrep","type":"formula","desc":"Fast code search"},
  {"name":"htop","type":"formula","desc":"Process viewer"},
  {"name":"btop","type":"formula","desc":"Resource monitor"},
  {"name":"lazygit","type":"formula","desc":"Git TUI"},
  {"name":"fd","type":"formula","desc":"Fast file finder"},
  {"name":"bat","type":"formula","desc":"Better cat with syntax"},
  {"name":"eza","type":"formula","desc":"Modern ls replacement"},
  {"name":"delta","type":"formula","desc":"Git diff with colors"},
  {"name":"tmux","type":"formula","desc":"Terminal multiplexer"},
  {"name":"tree","type":"formula","desc":"Directory visualizer"},
  {"name":"fzf","type":"formula","desc":"Fuzzy finder"},
  {"name":"tldr","type":"formula","desc":"Simplified man pages"},
  {"name":"glow","type":"formula","desc":"Markdown reader"},
  {"name":"ncdu","type":"formula","desc":"Disk usage analyzer"},
  {"name":"curl","type":"formula","desc":"HTTP transfer tool"},
  {"name":"wget","type":"formula","desc":"File downloader"},
  {"name":"httpie","type":"formula","desc":"HTTP client for APIs"},
  {"name":"nmap","type":"formula","desc":"Network scanner"},
  {"name":"mtr","type":"formula","desc":"Network diagnostic"},
  {"name":"watch","type":"formula","desc":"Execute periodically"},
  {"name":"orbstack","type":"cask","desc":"Docker alternative"},
  {"name":"lens","type":"cask","desc":"Kubernetes IDE"},
  {"name":"visual-studio-code","type":"cask","desc":"Code editor"},
  {"name":"warp","type":"cask","desc":"Modern terminal"},
  {"name":"iterm2","type":"cask","desc":"Terminal emulator"},
  {"name":"postman","type":"cask","desc":"API testing"},
  {"name":"wireshark","type":"cask","desc":"Network analyzer"},
  {"name":"rectangle","type":"cask","desc":"Window manager"},
  {"name":"raycast","type":"cask","desc":"Launcher and productivity"},
  {"name":"slack","type":"cask","desc":"Team communication"},
  {"name":"zoom","type":"cask","desc":"Video conferencing"},
  {"name":"notion","type":"cask","desc":"Notes and docs"},
  {"name":"obsidian","type":"cask","desc":"Knowledge base"},
  {"name":"1password","type":"cask","desc":"Password manager"}
]' WHERE id = 'ob-seed-devops-sre';

-- 13. Platform Engineer (was: 17 packages → enriched to: 58 packages)
UPDATE configs SET packages = '[
  {"name":"terraform","type":"formula","desc":"Infrastructure as code"},
  {"name":"terragrunt","type":"formula","desc":"Terraform wrapper"},
  {"name":"ansible","type":"formula","desc":"Config management"},
  {"name":"sops","type":"formula","desc":"Encrypted secrets editor"},
  {"name":"age","type":"formula","desc":"Modern file encryption"},
  {"name":"cosign","type":"formula","desc":"Container signing"},
  {"name":"syft","type":"formula","desc":"SBOM generator"},
  {"name":"grype","type":"formula","desc":"Vulnerability scanner"},
  {"name":"kubectl","type":"formula","desc":"Kubernetes CLI"},
  {"name":"helm","type":"formula","desc":"Kubernetes package manager"},
  {"name":"helmfile","type":"formula","desc":"Helm chart deployer"},
  {"name":"k9s","type":"formula","desc":"Kubernetes TUI"},
  {"name":"kubectx","type":"formula","desc":"Context switcher"},
  {"name":"kustomize","type":"formula","desc":"Config customizer"},
  {"name":"argocd","type":"formula","desc":"GitOps CD tool"},
  {"name":"flux","type":"formula","desc":"GitOps toolkit"},
  {"name":"awscli","type":"formula","desc":"AWS command line"},
  {"name":"eksctl","type":"formula","desc":"EKS manager"},
  {"name":"docker","type":"formula","desc":"Container engine"},
  {"name":"buildkit","type":"formula","desc":"Build toolkit"},
  {"name":"skopeo","type":"formula","desc":"Container image tool"},
  {"name":"vault","type":"formula","desc":"Secret management"},
  {"name":"consul","type":"formula","desc":"Service mesh"},
  {"name":"prometheus","type":"formula","desc":"Monitoring"},
  {"name":"jq","type":"formula","desc":"JSON processor"},
  {"name":"yq","type":"formula","desc":"YAML processor"},
  {"name":"git","type":"formula","desc":"Version control"},
  {"name":"gh","type":"formula","desc":"GitHub CLI"},
  {"name":"ripgrep","type":"formula","desc":"Fast search"},
  {"name":"fd","type":"formula","desc":"Fast finder"},
  {"name":"bat","type":"formula","desc":"Better cat"},
  {"name":"eza","type":"formula","desc":"Modern ls"},
  {"name":"delta","type":"formula","desc":"Git diff colors"},
  {"name":"lazygit","type":"formula","desc":"Git TUI"},
  {"name":"tmux","type":"formula","desc":"Terminal multiplexer"},
  {"name":"tree","type":"formula","desc":"Directory visualizer"},
  {"name":"fzf","type":"formula","desc":"Fuzzy finder"},
  {"name":"tldr","type":"formula","desc":"Simplified man"},
  {"name":"glow","type":"formula","desc":"Markdown reader"},
  {"name":"htop","type":"formula","desc":"Process viewer"},
  {"name":"btop","type":"formula","desc":"Resource monitor"},
  {"name":"ncdu","type":"formula","desc":"Disk analyzer"},
  {"name":"curl","type":"formula","desc":"HTTP tool"},
  {"name":"wget","type":"formula","desc":"File downloader"},
  {"name":"httpie","type":"formula","desc":"HTTP client"},
  {"name":"watch","type":"formula","desc":"Execute periodically"},
  {"name":"orbstack","type":"cask","desc":"Docker alternative"},
  {"name":"lens","type":"cask","desc":"Kubernetes IDE"},
  {"name":"visual-studio-code","type":"cask","desc":"Code editor"},
  {"name":"warp","type":"cask","desc":"Modern terminal"},
  {"name":"iterm2","type":"cask","desc":"Terminal emulator"},
  {"name":"postman","type":"cask","desc":"API testing"},
  {"name":"rectangle","type":"cask","desc":"Window manager"},
  {"name":"raycast","type":"cask","desc":"Launcher"},
  {"name":"slack","type":"cask","desc":"Team comm"},
  {"name":"notion","type":"cask","desc":"Notes"},
  {"name":"obsidian","type":"cask","desc":"Knowledge base"},
  {"name":"1password","type":"cask","desc":"Password manager"}
]' WHERE id = 'ob-seed-platform-eng';

-- 14. Data Science / ML (was: 13 packages → enriched to: 46 packages)
UPDATE configs SET packages = '[
  {"name":"python","type":"formula","desc":"Python interpreter"},
  {"name":"python@3.11","type":"formula","desc":"Python 3.11 LTS"},
  {"name":"uv","type":"formula","desc":"Fast Python package manager"},
  {"name":"ruff","type":"formula","desc":"Fast linter"},
  {"name":"jupyter","type":"formula","desc":"Interactive notebooks"},
  {"name":"ipython","type":"formula","desc":"Enhanced Python shell"},
  {"name":"pyenv","type":"formula","desc":"Python version manager"},
  {"name":"git","type":"formula","desc":"Version control"},
  {"name":"gh","type":"formula","desc":"GitHub CLI"},
  {"name":"git-lfs","type":"formula","desc":"Large file storage"},
  {"name":"jq","type":"formula","desc":"JSON processor"},
  {"name":"yq","type":"formula","desc":"YAML processor"},
  {"name":"wget","type":"formula","desc":"File downloader"},
  {"name":"curl","type":"formula","desc":"HTTP transfer tool"},
  {"name":"httpie","type":"formula","desc":"HTTP client"},
  {"name":"ripgrep","type":"formula","desc":"Fast code search"},
  {"name":"fd","type":"formula","desc":"Fast file finder"},
  {"name":"bat","type":"formula","desc":"Better cat with syntax"},
  {"name":"eza","type":"formula","desc":"Modern ls replacement"},
  {"name":"delta","type":"formula","desc":"Git diff with colors"},
  {"name":"lazygit","type":"formula","desc":"Git TUI"},
  {"name":"tmux","type":"formula","desc":"Terminal multiplexer"},
  {"name":"tree","type":"formula","desc":"Directory visualizer"},
  {"name":"htop","type":"formula","desc":"Process viewer"},
  {"name":"btop","type":"formula","desc":"Resource monitor"},
  {"name":"ncdu","type":"formula","desc":"Disk usage analyzer"},
  {"name":"tldr","type":"formula","desc":"Simplified man pages"},
  {"name":"glow","type":"formula","desc":"Markdown reader"},
  {"name":"fzf","type":"formula","desc":"Fuzzy finder"},
  {"name":"graphviz","type":"formula","desc":"Graph visualization"},
  {"name":"imagemagick","type":"formula","desc":"Image processing"},
  {"name":"ffmpeg","type":"formula","desc":"Video processing"},
  {"name":"miniconda","type":"cask","desc":"Conda environment manager"},
  {"name":"visual-studio-code","type":"cask","desc":"Code editor"},
  {"name":"pycharm","type":"cask","desc":"Python IDE"},
  {"name":"cursor","type":"cask","desc":"AI code editor"},
  {"name":"orbstack","type":"cask","desc":"Docker alternative"},
  {"name":"tableplus","type":"cask","desc":"Database GUI"},
  {"name":"warp","type":"cask","desc":"Modern terminal"},
  {"name":"iterm2","type":"cask","desc":"Terminal emulator"},
  {"name":"rectangle","type":"cask","desc":"Window manager"},
  {"name":"raycast","type":"cask","desc":"Launcher and productivity"},
  {"name":"slack","type":"cask","desc":"Team communication"},
  {"name":"zoom","type":"cask","desc":"Video conferencing"},
  {"name":"notion","type":"cask","desc":"Notes and docs"},
  {"name":"1password","type":"cask","desc":"Password manager"}
]' WHERE id = 'ob-seed-data-science';

-- 15. Security Engineer (was: 16 packages → enriched to: 52 packages)
UPDATE configs SET packages = '[
  {"name":"nmap","type":"formula","desc":"Network port scanner"},
  {"name":"masscan","type":"formula","desc":"Fast port scanner"},
  {"name":"nikto","type":"formula","desc":"Web server scanner"},
  {"name":"sqlmap","type":"formula","desc":"SQL injection tester"},
  {"name":"openssl","type":"formula","desc":"Crypto and TLS toolkit"},
  {"name":"gnupg","type":"formula","desc":"PGP encryption"},
  {"name":"age","type":"formula","desc":"Modern encryption"},
  {"name":"sops","type":"formula","desc":"Encrypted secrets"},
  {"name":"vault","type":"formula","desc":"Secret management"},
  {"name":"john","type":"formula","desc":"Password cracker"},
  {"name":"hydra","type":"formula","desc":"Login cracker"},
  {"name":"metasploit","type":"formula","desc":"Penetration testing"},
  {"name":"aircrack-ng","type":"formula","desc":"WiFi security"},
  {"name":"hashcat","type":"formula","desc":"Password recovery"},
  {"name":"tcpdump","type":"formula","desc":"Packet analyzer"},
  {"name":"mitmproxy","type":"formula","desc":"HTTP proxy"},
  {"name":"socat","type":"formula","desc":"Relay for sockets"},
  {"name":"netcat","type":"formula","desc":"TCP/UDP connections"},
  {"name":"git","type":"formula","desc":"Version control"},
  {"name":"gh","type":"formula","desc":"GitHub CLI"},
  {"name":"jq","type":"formula","desc":"JSON processor"},
  {"name":"yq","type":"formula","desc":"YAML processor"},
  {"name":"ripgrep","type":"formula","desc":"Fast code search"},
  {"name":"fd","type":"formula","desc":"Fast file finder"},
  {"name":"bat","type":"formula","desc":"Better cat with syntax"},
  {"name":"eza","type":"formula","desc":"Modern ls replacement"},
  {"name":"delta","type":"formula","desc":"Git diff with colors"},
  {"name":"lazygit","type":"formula","desc":"Git TUI"},
  {"name":"tmux","type":"formula","desc":"Terminal multiplexer"},
  {"name":"tree","type":"formula","desc":"Directory visualizer"},
  {"name":"htop","type":"formula","desc":"Process viewer"},
  {"name":"btop","type":"formula","desc":"Resource monitor"},
  {"name":"tldr","type":"formula","desc":"Simplified man pages"},
  {"name":"glow","type":"formula","desc":"Markdown reader"},
  {"name":"fzf","type":"formula","desc":"Fuzzy finder"},
  {"name":"curl","type":"formula","desc":"HTTP transfer tool"},
  {"name":"wget","type":"formula","desc":"File downloader"},
  {"name":"httpie","type":"formula","desc":"HTTP client"},
  {"name":"wireshark","type":"cask","desc":"Packet analyzer"},
  {"name":"burp-suite","type":"cask","desc":"Web security testing"},
  {"name":"owasp-zap","type":"cask","desc":"Web app scanner"},
  {"name":"charles","type":"cask","desc":"HTTP proxy"},
  {"name":"visual-studio-code","type":"cask","desc":"Code editor"},
  {"name":"ghidra","type":"cask","desc":"Reverse engineering"},
  {"name":"warp","type":"cask","desc":"Modern terminal"},
  {"name":"iterm2","type":"cask","desc":"Terminal emulator"},
  {"name":"rectangle","type":"cask","desc":"Window manager"},
  {"name":"raycast","type":"cask","desc":"Launcher and productivity"},
  {"name":"slack","type":"cask","desc":"Team communication"},
  {"name":"discord","type":"cask","desc":"Security community"},
  {"name":"notion","type":"cask","desc":"Notes and docs"},
  {"name":"1password","type":"cask","desc":"Password manager"}
]' WHERE id = 'ob-seed-security-eng';

-- 16. Game Dev - Unity (was: 13 packages → enriched to: 35 packages)
UPDATE configs SET packages = '[
  {"name":"git","type":"formula","desc":"Version control"},
  {"name":"git-lfs","type":"formula","desc":"Large file storage"},
  {"name":"gh","type":"formula","desc":"GitHub CLI"},
  {"name":"cmake","type":"formula","desc":"Cross-platform build system"},
  {"name":"ffmpeg","type":"formula","desc":"Video/audio processor"},
  {"name":"imagemagick","type":"formula","desc":"Image processing CLI"},
  {"name":"node","type":"formula","desc":"JavaScript runtime"},
  {"name":"python","type":"formula","desc":"Python interpreter"},
  {"name":"jq","type":"formula","desc":"JSON processor"},
  {"name":"tree","type":"formula","desc":"Directory visualizer"},
  {"name":"lazygit","type":"formula","desc":"Git TUI"},
  {"name":"ripgrep","type":"formula","desc":"Fast code search"},
  {"name":"fd","type":"formula","desc":"Fast file finder"},
  {"name":"bat","type":"formula","desc":"Better cat with syntax"},
  {"name":"eza","type":"formula","desc":"Modern ls replacement"},
  {"name":"delta","type":"formula","desc":"Git diff with colors"},
  {"name":"fzf","type":"formula","desc":"Fuzzy finder"},
  {"name":"tldr","type":"formula","desc":"Simplified man pages"},
  {"name":"htop","type":"formula","desc":"Process viewer"},
  {"name":"wget","type":"formula","desc":"File downloader"},
  {"name":"curl","type":"formula","desc":"HTTP transfer tool"},
  {"name":"unity-hub","type":"cask","desc":"Unity version manager"},
  {"name":"blender","type":"cask","desc":"3D modeling and animation"},
  {"name":"visual-studio-code","type":"cask","desc":"Code editor"},
  {"name":"rider","type":"cask","desc":"Unity C# IDE"},
  {"name":"obs","type":"cask","desc":"Screen recording"},
  {"name":"audacity","type":"cask","desc":"Audio editor"},
  {"name":"gimp","type":"cask","desc":"Image editor"},
  {"name":"rectangle","type":"cask","desc":"Window manager"},
  {"name":"raycast","type":"cask","desc":"Launcher and productivity"},
  {"name":"discord","type":"cask","desc":"Game dev community"},
  {"name":"slack","type":"cask","desc":"Team communication"},
  {"name":"notion","type":"cask","desc":"Notes and docs"},
  {"name":"obsidian","type":"cask","desc":"Knowledge base"},
  {"name":"1password","type":"cask","desc":"Password manager"}
]' WHERE id = 'ob-seed-unity-gamedev';

-- 17. Blockchain / Web3 (was: 14 packages → enriched to: 44 packages)
UPDATE configs SET packages = '[
  {"name":"node","type":"formula","desc":"JavaScript runtime"},
  {"name":"node@20","type":"formula","desc":"Node.js LTS 20"},
  {"name":"pnpm","type":"formula","desc":"Fast package manager"},
  {"name":"bun","type":"formula","desc":"Fast JS runtime"},
  {"name":"git","type":"formula","desc":"Version control"},
  {"name":"gh","type":"formula","desc":"GitHub CLI"},
  {"name":"jq","type":"formula","desc":"JSON processor"},
  {"name":"yq","type":"formula","desc":"YAML processor"},
  {"name":"ripgrep","type":"formula","desc":"Fast code search"},
  {"name":"fd","type":"formula","desc":"Fast file finder"},
  {"name":"bat","type":"formula","desc":"Better cat with syntax"},
  {"name":"eza","type":"formula","desc":"Modern ls replacement"},
  {"name":"delta","type":"formula","desc":"Git diff with colors"},
  {"name":"lazygit","type":"formula","desc":"Git TUI"},
  {"name":"curl","type":"formula","desc":"HTTP transfer tool"},
  {"name":"wget","type":"formula","desc":"File downloader"},
  {"name":"httpie","type":"formula","desc":"HTTP client for APIs"},
  {"name":"python","type":"formula","desc":"Python interpreter"},
  {"name":"rustup","type":"formula","desc":"Rust toolchain installer"},
  {"name":"cmake","type":"formula","desc":"Cross-platform build system"},
  {"name":"protobuf","type":"formula","desc":"Protocol buffers"},
  {"name":"tmux","type":"formula","desc":"Terminal multiplexer"},
  {"name":"tree","type":"formula","desc":"Directory visualizer"},
  {"name":"htop","type":"formula","desc":"Process viewer"},
  {"name":"btop","type":"formula","desc":"Resource monitor"},
  {"name":"fzf","type":"formula","desc":"Fuzzy finder"},
  {"name":"tldr","type":"formula","desc":"Simplified man pages"},
  {"name":"glow","type":"formula","desc":"Markdown reader"},
  {"name":"ncdu","type":"formula","desc":"Disk usage analyzer"},
  {"name":"visual-studio-code","type":"cask","desc":"Code editor"},
  {"name":"cursor","type":"cask","desc":"AI code editor"},
  {"name":"google-chrome","type":"cask","desc":"MetaMask browser"},
  {"name":"arc","type":"cask","desc":"Productivity browser"},
  {"name":"orbstack","type":"cask","desc":"Docker alternative"},
  {"name":"postman","type":"cask","desc":"API testing"},
  {"name":"ganache","type":"cask","desc":"Local blockchain"},
  {"name":"warp","type":"cask","desc":"Modern terminal"},
  {"name":"iterm2","type":"cask","desc":"Terminal emulator"},
  {"name":"rectangle","type":"cask","desc":"Window manager"},
  {"name":"raycast","type":"cask","desc":"Launcher and productivity"},
  {"name":"slack","type":"cask","desc":"Team communication"},
  {"name":"discord","type":"cask","desc":"Web3 community"},
  {"name":"notion","type":"cask","desc":"Notes and docs"},
  {"name":"1password","type":"cask","desc":"Password manager"}
]' WHERE id = 'ob-seed-web3-dev';

-- 18. Designer who Codes (was: 16 packages → enriched to: 44 packages)
UPDATE configs SET packages = '[
  {"name":"node","type":"formula","desc":"JavaScript runtime"},
  {"name":"pnpm","type":"formula","desc":"Fast package manager"},
  {"name":"bun","type":"formula","desc":"Fast JS runtime"},
  {"name":"imagemagick","type":"formula","desc":"Image processing CLI"},
  {"name":"ffmpeg","type":"formula","desc":"Video/audio processor"},
  {"name":"webp","type":"formula","desc":"WebP image format"},
  {"name":"optipng","type":"formula","desc":"PNG optimizer"},
  {"name":"jpegoptim","type":"formula","desc":"JPEG optimizer"},
  {"name":"git","type":"formula","desc":"Version control"},
  {"name":"gh","type":"formula","desc":"GitHub CLI"},
  {"name":"jq","type":"formula","desc":"JSON processor"},
  {"name":"lazygit","type":"formula","desc":"Git TUI"},
  {"name":"ripgrep","type":"formula","desc":"Fast code search"},
  {"name":"fd","type":"formula","desc":"Fast file finder"},
  {"name":"bat","type":"formula","desc":"Better cat with syntax"},
  {"name":"eza","type":"formula","desc":"Modern ls replacement"},
  {"name":"delta","type":"formula","desc":"Git diff with colors"},
  {"name":"fzf","type":"formula","desc":"Fuzzy finder"},
  {"name":"tree","type":"formula","desc":"Directory visualizer"},
  {"name":"tldr","type":"formula","desc":"Simplified man pages"},
  {"name":"glow","type":"formula","desc":"Markdown reader"},
  {"name":"htop","type":"formula","desc":"Process viewer"},
  {"name":"curl","type":"formula","desc":"HTTP transfer tool"},
  {"name":"wget","type":"formula","desc":"File downloader"},
  {"name":"figma","type":"cask","desc":"Design collaboration"},
  {"name":"sketch","type":"cask","desc":"Vector design tool"},
  {"name":"visual-studio-code","type":"cask","desc":"Code editor"},
  {"name":"cursor","type":"cask","desc":"AI code editor"},
  {"name":"google-chrome","type":"cask","desc":"Web browser"},
  {"name":"arc","type":"cask","desc":"Productivity browser"},
  {"name":"firefox","type":"cask","desc":"Testing browser"},
  {"name":"cleanshot","type":"cask","desc":"Screenshot utility"},
  {"name":"shottr","type":"cask","desc":"Quick annotation tool"},
  {"name":"pixelsnap","type":"cask","desc":"Measurement tool"},
  {"name":"imageoptim","type":"cask","desc":"Image optimizer"},
  {"name":"handbrake","type":"cask","desc":"Video transcoder"},
  {"name":"warp","type":"cask","desc":"Modern terminal"},
  {"name":"iterm2","type":"cask","desc":"Terminal emulator"},
  {"name":"rectangle","type":"cask","desc":"Window manager"},
  {"name":"raycast","type":"cask","desc":"Launcher and productivity"},
  {"name":"slack","type":"cask","desc":"Team communication"},
  {"name":"discord","type":"cask","desc":"Design community"},
  {"name":"notion","type":"cask","desc":"Notes and docs"},
  {"name":"1password","type":"cask","desc":"Password manager"}
]' WHERE id = 'ob-seed-design-dev';

-- 19. Student / Beginner (was: 12 packages → enriched to: 30 packages)
UPDATE configs SET packages = '[
  {"name":"git","type":"formula","desc":"Version control"},
  {"name":"gh","type":"formula","desc":"GitHub CLI"},
  {"name":"node","type":"formula","desc":"JavaScript runtime"},
  {"name":"python","type":"formula","desc":"Python interpreter"},
  {"name":"jq","type":"formula","desc":"JSON processor"},
  {"name":"tree","type":"formula","desc":"Directory visualizer"},
  {"name":"bat","type":"formula","desc":"Better cat with syntax"},
  {"name":"eza","type":"formula","desc":"Modern ls replacement"},
  {"name":"delta","type":"formula","desc":"Git diff with colors"},
  {"name":"lazygit","type":"formula","desc":"Git TUI"},
  {"name":"fzf","type":"formula","desc":"Fuzzy finder"},
  {"name":"ripgrep","type":"formula","desc":"Fast code search"},
  {"name":"fd","type":"formula","desc":"Fast file finder"},
  {"name":"tldr","type":"formula","desc":"Simplified man pages"},
  {"name":"glow","type":"formula","desc":"Markdown reader"},
  {"name":"htop","type":"formula","desc":"Process viewer"},
  {"name":"curl","type":"formula","desc":"HTTP transfer tool"},
  {"name":"wget","type":"formula","desc":"File downloader"},
  {"name":"httpie","type":"formula","desc":"HTTP client"},
  {"name":"visual-studio-code","type":"cask","desc":"Code editor"},
  {"name":"iterm2","type":"cask","desc":"Terminal emulator"},
  {"name":"warp","type":"cask","desc":"Modern terminal"},
  {"name":"google-chrome","type":"cask","desc":"Web browser"},
  {"name":"rectangle","type":"cask","desc":"Window manager"},
  {"name":"raycast","type":"cask","desc":"Launcher and productivity"},
  {"name":"postman","type":"cask","desc":"API testing"},
  {"name":"slack","type":"cask","desc":"Team communication"},
  {"name":"discord","type":"cask","desc":"Developer community"},
  {"name":"notion","type":"cask","desc":"Notes and docs"},
  {"name":"1password","type":"cask","desc":"Password manager"}
]' WHERE id = 'ob-seed-starter-kit';

-- 20. Content Creator / Tech Writer (was: 14 packages → enriched to: 42 packages)
UPDATE configs SET packages = '[
  {"name":"hugo","type":"formula","desc":"Static site generator"},
  {"name":"jekyll","type":"formula","desc":"Static site generator"},
  {"name":"pandoc","type":"formula","desc":"Document converter"},
  {"name":"asciinema","type":"formula","desc":"Terminal recorder"},
  {"name":"ttyd","type":"formula","desc":"Web terminal"},
  {"name":"ffmpeg","type":"formula","desc":"Video/audio processor"},
  {"name":"imagemagick","type":"formula","desc":"Image processing CLI"},
  {"name":"optipng","type":"formula","desc":"PNG optimizer"},
  {"name":"jpegoptim","type":"formula","desc":"JPEG optimizer"},
  {"name":"git","type":"formula","desc":"Version control"},
  {"name":"gh","type":"formula","desc":"GitHub CLI"},
  {"name":"node","type":"formula","desc":"JavaScript runtime"},
  {"name":"pnpm","type":"formula","desc":"Fast package manager"},
  {"name":"tree","type":"formula","desc":"Directory visualizer"},
  {"name":"bat","type":"formula","desc":"Better cat with syntax"},
  {"name":"eza","type":"formula","desc":"Modern ls replacement"},
  {"name":"delta","type":"formula","desc":"Git diff with colors"},
  {"name":"lazygit","type":"formula","desc":"Git TUI"},
  {"name":"ripgrep","type":"formula","desc":"Fast code search"},
  {"name":"fd","type":"formula","desc":"Fast file finder"},
  {"name":"fzf","type":"formula","desc":"Fuzzy finder"},
  {"name":"tldr","type":"formula","desc":"Simplified man pages"},
  {"name":"glow","type":"formula","desc":"Markdown reader"},
  {"name":"jq","type":"formula","desc":"JSON processor"},
  {"name":"yq","type":"formula","desc":"YAML processor"},
  {"name":"htop","type":"formula","desc":"Process viewer"},
  {"name":"curl","type":"formula","desc":"HTTP transfer tool"},
  {"name":"wget","type":"formula","desc":"File downloader"},
  {"name":"obs","type":"cask","desc":"Screen recording"},
  {"name":"visual-studio-code","type":"cask","desc":"Code editor"},
  {"name":"obsidian","type":"cask","desc":"Knowledge base"},
  {"name":"notion","type":"cask","desc":"Notes and docs"},
  {"name":"cleanshot","type":"cask","desc":"Screenshot utility"},
  {"name":"shottr","type":"cask","desc":"Quick annotation tool"},
  {"name":"imageoptim","type":"cask","desc":"Image optimizer"},
  {"name":"handbrake","type":"cask","desc":"Video transcoder"},
  {"name":"google-chrome","type":"cask","desc":"Web browser"},
  {"name":"warp","type":"cask","desc":"Modern terminal"},
  {"name":"iterm2","type":"cask","desc":"Terminal emulator"},
  {"name":"rectangle","type":"cask","desc":"Window manager"},
  {"name":"raycast","type":"cask","desc":"Launcher and productivity"},
  {"name":"slack","type":"cask","desc":"Team communication"}
]' WHERE id = 'ob-seed-tech-writer';
